### ISSUE TITLE
갤럭시S6에서 메뉴 버튼이 없다니!!

### ISSUE THREAD

**Issue by newmbewb** [clover3/isb#64]
갤럭시S6에서 메뉴 버튼이 없다니!! 갤럭시S6에서 메뉴 버튼이 없다니!!
으아니 이게 무슨 소리요 삼성 양반!!
슬비앱이 ㄱㅈ라니!

**Comment by newmbewb** [comment]
당장 생각나는 대안
1. 그냥 메뉴 버튼 추가 (보드 검색 창 & 보드 제목)
 - 좀 추리해보이긴 함.
2. 슬라이딩 메뉴 추가
 - 1 보다는 나아 보이기는 하는데 보통 슬라이드 메뉴는 탭이 여러개/화면 이동할 때 많이 쓰이지 않나? 보드 목록 새로고침 같은 경우에는 화면 이동이 아니니 어색할 수도.
기타. Search New Posts 버튼 대신에 맨 위에를 끌어 잡아당김으로써 (크롬에서 새로고침 하듯이) 기능을 수행할 수 있도록 하면 좋을 듯. 같은 방법을 보드에서 새 글 쓸때 사용하도록 할 수도 있을 듯.

**Comment by clover3** [comment]
헐? 근데 소프트웨어 메뉴키 비슷한거 뜨지 않음??
